### ISSUE TITLE
A very dangerous bug....

### ISSUE THREAD

**Issue by lanyizi** [louisdx/cnc-replayreaders#1]
In the function "fix_replay_file", cnc3reader_impl.cpp,
inside the block
"if (myfile.eof() || filesize - myfile.tellg() < chunk_size + 4)",
there isn't any return statement after
"std::cerr << "Error: Specified rescue position (" << opts.fixpos << ") does not point to a good chunk. Aborting." << std::endl;"

Even if you have written "Aborting", there isn't actually any "return" statement.

The function will continue to write data to the fixed replay file, until it fill completely the hard disk....

**Comment by louisdx** [comment]
Thanks a lot for reporting! Fixed by bf5c7a8.
